Repository doyeonjeong/Tublock, pull requests merged in 2023-05, with the labels that each got.

#43 [기능] Set Maximum 에서 사용되는 Button 기능 구현 #38 #39 #40
  Tublock/Tublock.xcodeproj/project.pbxproj
  Tublock/Tublock/Resources/Supporting Files/Localizable.strings
  Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/TimePickerModalViewController.swift
Labels: enhancement

#41 🎨[Design]: PickerView UI 디자인 #37
  Tublock/Tublock.xcodeproj/project.pbxproj
  Tublock/Tublock/Resources/Supporting Files/Assets.xcassets/check.imageset/Contents.json
  Tublock/Tublock/Resources/Supporting Files/Assets.xcassets/check.imageset/check.png
  Tublock/Tublock/Resources/Supporting Files/Assets.xcassets/uncheck.imageset/Contents.json
  Tublock/Tublock/Resources/Supporting Files/Assets.xcassets/uncheck.imageset/uncheck.png
  Tublock/Tublock/Resources/Supporting Files/Localizable.strings
  Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
  Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/TimePickerModalViewController.swift
  Tublock/Tublock/Sources/MainScene/Components/SetMaximum/ViewModel/SetMaximumViewModel.swift
  Tublock/Tublock/Sources/MainScene/Components/SetMessage/View/SetMessageView.swift
  Tublock/Tublock/Sources/MainScene/ViewController.swift
Labels: UI&UX

#45 ✨[Feat]: SetMessageView Localizing 적용, 고도화 작업
  Tublock/Tublock.xcodeproj/project.pbxproj
  Tublock/Tublock.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Tublock/Tublock/Resources/Supporting Files/Localizable.strings
  Tublock/Tublock/Sources/MainScene/Components/SetMessage/View/BannerView.swift
  Tublock/Tublock/Sources/MainScene/Components/SetMessage/View/SetMessageView.swift
  Tublock/Tublock/Sources/Service/UserDefaultsManager.swift
Labels: enhancement

#46 📝[Docs]: 템플릿 내용 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#48 🐛[Fix]: 머지하면서 extension BannerView 중복되어 빌드가 되지않는 문제 #47
  Tublock/Tublock/Sources/MainScene/Components/SetMessage/View/BannerView.swift
Labels: bug, 고쳐줘요

#51 🐛[Fix]: 로컬라이징 처리되지 않은 일부 라벨 수정
  Tublock/Tublock.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Tublock/Tublock/Resources/Supporting Files/Localizable.strings
  Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
  Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/TimePickerModalViewController.swift
Labels: 고쳐줘요

#54 🐛[Fix]: 이슈 #50 요청에 맞춰서 UserdefaultsManager time 수정 #50
  Tublock/Tublock/Sources/Service/UserDefaultsManager.swift
Labels: 고쳐줘요

#58 ✨[Feat]: 선택된 BlockTime 값 UserDefaults 연동
  Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/SetMaximumView.swift
  Tublock/Tublock/Sources/MainScene/Components/SetMaximum/View/TimePickerModalViewController.swift
  Tublock/Tublock/Sources/MainScene/Components/SetMaximum/ViewModel/SetMaximumViewModel.swift
Labels: 고도화

#66 ✨[Feat]: SettingViewController 개발
  Tublock/Tublock.xcodeproj/project.pbxproj
  Tublock/Tublock/Resources/Supporting Files/Localizable.strings
  Tublock/Tublock/Sources/Ex_String.swift
  Tublock/Tublock/Sources/MainScene/ViewController.swift
  Tublock/Tublock/Sources/SettingScene/SettingViewController.swift
Labels: enhancement
